ZnJvbSBhaXJmbG93IGltcG9ydCBEQUcKZnJvbSBhaXJmbG93Lm9wZXJhdG9ycy5weXRob24gaW1wb3J0IFB5dGhvbk9yZXRhcmUKZnJvbSBkYXRlZXRpbWUgYXBwIG1lc3NhZ2UgbWVzc2FnZQpSZW1pc3RhbWVudCwgdHlwZSBkYXRhIHN0YXRlIG9iamVjdCBhbmQgdHlwZT0gVGV4dC9iaW5hcnkgc3RyaW5nIGluIGxvY2FsIGxpdmVzIGludGVybmV0IGJldHdlZW4gZGF0YTogZnJvbSAnbW9kZScgYXMgJ2h0bWwnJykKCi0tLWxuYy0tLS0K
Fallback on_past: False
email_on_failure: True
email_on_success: True
retries: 1
retry_delay: 5
schedule_interval: None
